config:
  - type: helm
    spec:
    - repository: helm-hosted
      path: requirements.yaml
      auto-update: true
  - type: pip
    spec:
    - repository: pypi-group
      path: requirements.txt
      auto-update: false